### ISSUE TITLE
Create a REPORT DESCRIPTION screen 

### ISSUE THREAD

**Issue by bernbecht** [bernbecht/vigilant-android#1]
## Tasks
- [x] create flow to the screen
  - [x] pin on map;
  - [x] snippet;
  - [x] snippet clickable;
- [ ]  create layout's structure:
  - [ ] button **...**
  - [x] username 
  - [x] photo 
  - [x] address
  - [x] date
  - [x] description
  - [x] category
  - [x] button **bothered**
- [ ]  style it;
  - [x] find camera aspect;
- [ ]  make buttons clickable
  - [ ] function;
  - [ ] click effect;
- [x] Iconography;
