### ISSUE TITLE
Putting Reports on Map

### ISSUE THREAD

**Issue by bernbecht** [bernbecht/vigilant-android#13]
## Tasks 
- [x] Retrieve all the reports with FALSE inappropriate
- [x] Put the reports on the map
- [x] Send to the Report Description
- [x] Put the icons on the Google Maps
- [x] put image
- [x] implement **bothered button**
  - [x] constrain one bother per user per problem
  - [x] check if user liked this problem to set button
  - [x] undo action for**Bother button**
### Pendencies
- Modeling the Tables for serializing and persisting them into the app
- Get country name
- Innapropriate button
- change the icon's style

**Comment by bernbecht** [comment]
# Important!

Actually I am sending the objectId to DescriptionActivity to do a new request. It should be passed the object.
So, modeling objects to be serialized and then passed by an intent is needed.
