### ISSUE TITLE
Connection Detection and Treating Errors

### ISSUE THREAD

**Issue by bernbecht** [bernbecht/vigilant-android#17]
## Tasks
- [x] class for detecting the connection status
- [x] create procedure for connection status on MapActivity
- [x] limit camera
- [x] limit addReport
- [x] limit Loggin
- [x] limit change email
- [x] limit for Bothered Button
- [x] limit for solved
- [x] limit for inappropriate
