### ISSUE TITLE
Create a REPORT DESCRIPTION screen 

### ISSUE THREAD

**Issue by bernbecht** [bernbecht/vigilant-android#3]
## Tasks
- [x] create flow to the screen
  - [x] pin on map;
  - [x] snippet;
  - [x] snippet clickable;
- [x]  create layout's structure:
  - [x] button **...**
  - [x] username 
  - [x] photo 
  - [x] address
  - [x] date
  - [x] description
  - [x] category
  - [x] button **bothered**
- [x]  style it;
  - [x] find camera aspect;
- [x] Iconography;
## Pendencies

Create a REPORT DESCRIPTION screen [refactor] #4
