### ISSUE TITLE
Login with Facebook

### ISSUE THREAD

**Issue by bernbecht** [bernbecht/vigilant-android#6]
## Tasks
- [x] POC about Facebook SDK
  - [x] import Facebook SDK to a project
  - [x] do a simple login
  - [x] customize login button
  - [x] activity flow with back button and avoiding the login screen if logged
- [x] Implementing on **Vigilant Project**
  - [x] import Facebook SDK to the project;
  - [x] create APP on Facebook and setup the keys on Android
  - [x] make a login
  - [x] manage flow
  - [x] create logout
  - [x] custom button facebook
  - [x] create **shared preferences** para _logged_
  - [x] test login behavior
## Pendencies
- [x] put the event of changing facebook's button background resource to another event. Perhaps **onAttach()**
- [x] create an utility class for handing the access to _SharedPreferences_

**Comment by bernbecht** [comment]
For the flow, use FRAGMENTS both for the login and the authenticated screen. When **onResume** or **onCreate**, check is there is a user and put the correct fragment.

For storing the **facebook user's object** is a good idea used Shared Preferences

**Comment by bernbecht** [comment]
For using **fragments** I needed to do an **POC**

**Comment by bernbecht** [comment]
**Remember**: _(FragmentTransaction).addToStack(null)_ makes you record the previous state before _FragmentTransaction.commit()_

**Comment by bernbecht** [comment]
**Remember**: if you are going to use **Support Library** for your _fragments_ use **ALL** with support.

**Comment by bernbecht** [comment]
As you can't have a _fragment_ inside another _fragment_, **LoginActivity** will have two _fragments_: the login itself and the form for setting the _username_.

The flow:

1) login screen <----------> 2) OAUTH screen --------> 3) username form screen -------> 4) map

1) fragment
2) it arranges itself
3) fragment replacement without _.addToStack()_ 
4) _startIntent()_ finishing **loginActivity**

### UPDATE

The flow:

1) login screen <----------> 2) OAUTH screen --------> 3) username form screen -------> 4) map

1) fragment and finishes itself at the end
2) it arranges itself
3) activity. It finishes itself at the end;
4) activity

**Comment by bernbecht** [comment]
For **the flow** instead killing the activity, I am using: 

```
intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
startActivity(intent);
```

This make no possible to return to the previous activity

**Comment by bernbecht** [comment]
Apparently, the login behavior (opening, closing and whatever) is **o.k**

**Comment by bernbecht** [comment]
#### About **pendency onAttach()**

How the login screen's was change for **logging just with Facebook** there is no reason to think when to change the button's background.

Code for it:

_LoginActivity.java_

```
@Override
    public void onCreate(Bundle savedInstanceState) {
   ...
    //Change the Facebook' button background
    LoginButton button = (LoginButton) findViewById(R.id.login_facebook_button);
    button.setBackgroundResource(R.drawable.ic_facebook_login);
    button.setCompoundDrawablesWithIntrinsicBounds(0, 0, 0, 0);
 }
```
