### ISSUE TITLE
Creating the cloud with Parse

### ISSUE THREAD

**Issue by bernbecht** [bernbecht/vigilant-android#8]
## Tasks
- Setting SDK
  - [x] import SDK to the project
  - [x] create a mock cloud with parse
  - [x] test your monster
- Parse
  - [x] login with _ParseFacebookUtils_
  - [x] getting a GraphUser
  - [x] getting an user from Parse
  - [x] persist user on app when logged
  - [x] create button for the login screen
  - [x] update logout method
  - [x] save extra info about user when new user
  - [x] set nickname
  - [x] check if the registered user has a nickname when he is logging 
  - [x] regex for checking nickname
  - [x] check if there is anybody with the same nickname

**Comment by bernbecht** [comment]
I created a table called **User** on Parse. So, the authentication rules are mine.

**Comment by bernbecht** [comment]
Don't fuck the police: I am using the Parse login :/

**Comment by bernbecht** [comment]
**Drawables** for the facebook login button are from the Facebook SDK
